"""
Texture Redirector
==================
Scans your game resource folder for .mgraphobject files,
shows them in the left panel, and mirrors your mod folder
contents in the right panel.

Place this script alongside the output_jsons/ folder (generated by split_mgraphobjects.py).
"""

import sys, os, json, re, shutil, threading
import tkinter as tk
from tkinter import ttk, filedialog, messagebox
from pathlib import Path

# ── Config ─────────────────────────────────────────────────────────────────────
JSON_FOLDER     = "output_jsons"
PREFS_JSON_PATH = "texture_redirector_prefs.json"

# Texture suffixes we care about renaming (others like dn_* are generic, skip)
TEXTURE_SUFFIXES = ("_d.dds", "_n.dds", "_m.dds", "_reg_mask.dds", "_mask.dds", "_masks.dds", "_region_mask.dds", "_region_masks.dds")

# ── Colours ────────────────────────────────────────────────────────────────────
BG       = "#0e0f14"
PANEL    = "#161822"
BORDER   = "#2a2d3e"
ACCENT   = "#4fc3f7"
ACCENT2  = "#80cbc4"
WARN     = "#ffb74d"
SUCCESS  = "#a5d6a7"
ERROR    = "#ef9a9a"
TEXT     = "#e8eaf6"
MUTED    = "#757997"
ENTRY_BG = "#1e2030"
BTN_BG   = "#263859"
BTN_HOV  = "#2e4470"
MONO     = "Consolas"

# ── Type colours ───────────────────────────────────────────────────────────────
TYPE_COLORS = {
    "gear":             "#ce93d8",
    "weapon":           "#ef9a9a",
    "character":        "#80cbc4",
    "prop":             "#ffcc80",
    "effect":           "#80deea",
    "building":         "#a5d6a7",
    "microdetail":      "#bcaaa4",
    "light":            "#fff59d",
    "interior":         "#b0bec5",
    "interiorwalls":    "#b0bec5",
    "road":             "#9e9e9e",
    "roadparts":        "#9e9e9e",
    "sidewalk":         "#9e9e9e",
    "sidewalkparts":    "#9e9e9e",
    "walls":            "#9e9e9e",
    "playerrealization":"#f48fb1",
}
TYPE_COLOR_DEFAULT = "#e8eaf6"

# ── Package colours ────────────────────────────────────────────────────────────
PKG_COLORS = {
    "base_game": "#4fc3f7",
    "dlc1":      "#a5d6a7",
    "dlc2":      "#ffb74d",
    "dlc3":      "#f06292",
    "rogue":     "#ce93d8",
    "snowdrop":  "#80deea",
    "vendor":    "#bcaaa4",
}
PKG_COLOR_DEFAULT = "#757997"


# ── Custom dialog ─────────────────────────────────────────────────────────────

def themed_error(parent, title, message):
    """Themed error dialog matching the app colour scheme."""
    dlg = tk.Toplevel(parent)
    dlg.title(title)
    dlg.configure(bg=BG)
    dlg.resizable(False, False)
    dlg.grab_set()
    dlg.focus_set()

    # Centre on parent
    parent.update_idletasks()
    pw, ph = parent.winfo_width(), parent.winfo_height()
    px, py = parent.winfo_rootx(), parent.winfo_rooty()
    w, h = 460, 210
    dlg.geometry(f"{w}x{h}+{px + (pw - w) // 2}+{py + (ph - h) // 2}")

    # Title bar strip
    bar = tk.Frame(dlg, bg=ERROR, height=4)
    bar.pack(fill="x")

    # Header
    hdr = tk.Frame(dlg, bg=PANEL)
    hdr.pack(fill="x")
    tk.Label(hdr, text=f"  ✕  {title}", bg=PANEL, fg=ERROR,
             font=("Segoe UI", 10, "bold"), pady=10, anchor="w"
             ).pack(fill="x", padx=10)
    tk.Frame(dlg, bg=BORDER, height=1).pack(fill="x")

    # Message
    body = tk.Frame(dlg, bg=BG)
    body.pack(fill="both", expand=True, padx=20, pady=16)
    tk.Label(body, text=message, bg=BG, fg=TEXT,
             font=("Segoe UI", 9), justify="left", anchor="w", wraplength=400
             ).pack(fill="x")

    # OK button
    tk.Frame(dlg, bg=BORDER, height=1).pack(fill="x")
    btn_row = tk.Frame(dlg, bg=PANEL)
    btn_row.pack(fill="x", pady=10)

    ok_container = tk.Frame(btn_row, bg=BTN_BG, cursor="hand2")
    ok_container.pack(anchor="center")

    ok_label = tk.Label(ok_container, text="  OK  ", bg=BTN_BG, fg=ACCENT,
                         font=("Segoe UI", 9, "bold"), padx=208, pady=6)
    ok_label.pack()

    def _on_enter(e):
        ok_container.config(bg=BTN_HOV)
        ok_label.config(bg=BTN_HOV)

    def _on_leave(e):
        ok_container.config(bg=BTN_BG)
        ok_label.config(bg=BTN_BG)

    def _on_click(e):
        dlg.destroy()

    for widget in (ok_container, ok_label):
        widget.bind("<Enter>", _on_enter)
        widget.bind("<Leave>", _on_leave)
        widget.bind("<Button-1>", _on_click)

    dlg.bind("<Return>", lambda _: dlg.destroy())
    dlg.bind("<Escape>", lambda _: dlg.destroy())
    dlg.wait_window()


# ── Helpers ────────────────────────────────────────────────────────────────────

def get_base_dir():
    if getattr(sys, "frozen", False):
        return Path(sys.executable).parent
    return Path(__file__).parent


def load_all_json_data():
    """Load all JSONs from output_jsons/ and return combined data keyed by obj_type -> package -> entries."""
    folder = get_base_dir() / JSON_FOLDER
    combined = {}
    if not folder.exists():
        return combined
    for json_file in sorted(folder.glob("*.json")):
        try:
            with open(json_file, "r", encoding="utf-8") as f:
                data = json.load(f)
            for obj_type, packages in data.items():
                if obj_type not in combined:
                    combined[obj_type] = {}
                for package, entries in packages.items():
                    combined[obj_type][package] = entries
        except Exception:
            pass
    return combined


def load_prefs():
    p = get_base_dir() / PREFS_JSON_PATH
    if p.exists():
        try:
            with open(p, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            pass
    return {}


def save_prefs(prefs):
    p = get_base_dir() / PREFS_JSON_PATH
    try:
        with open(p, "w", encoding="utf-8") as f:
            json.dump(prefs, f, indent=2)
    except Exception:
        pass


def build_stem_index(all_data):
    """mgraphobject stem (lowercase) -> enriched entry dict (includes slot and package)."""
    index = {}
    for obj_type, packages in all_data.items():
        for package, entries in packages.items():
            for entry in entries:
                for mg in entry.get("mgraphobject", []):
                    index[mg.lower()] = {"slot": obj_type, "package": package, **entry}
    return index


def scan_folder(folder: str):
    """Return list of Path objects for every .mgraphobject found recursively."""
    hits = []
    for root, _, files in os.walk(folder):
        for f in files:
            if f.lower().endswith(".mgraphobject"):
                hits.append(Path(root) / f)
    return hits


def find_textures_in_folder(folder: str, texture_names: list) -> dict:
    """
    Walk folder recursively and check which texture filenames exist.
    Returns { filename: Path|None } -- None means not found.
    """
    index = {}
    for root, _, files in os.walk(folder):
        for f in files:
            index[f.lower()] = Path(root) / f
    return {t: index.get(t.lower()) for t in texture_names}


def extract_dds_from_binary(mgraph_path: Path) -> list:
    """
    Parse a .mgraphobject binary and extract all embedded DDS paths.
    Returns a deduplicated list of tuples: (full_path, filename)
    preserving order of first appearance.
    """
    try:
        data = mgraph_path.read_bytes()
    except Exception:
        return []
    seen = set()
    results = []
    for m in re.finditer(rb'[^\x00]{4,512}\.dds\x00', data):
        try:
            full_path = m.group(0)[:-1].decode("ascii")
        except UnicodeDecodeError:
            continue
        fname = full_path.split("/")[-1].split("\\")[-1]
        if fname.lower() not in seen:
            seen.add(fname.lower())
            results.append((full_path, fname))
    return results


def is_targeted_texture(filename: str) -> bool:
    """Return True if this texture filename ends with a suffix we rename."""
    low = filename.lower()
    return any(low.endswith(s) for s in TEXTURE_SUFFIXES)


def get_texture_suffix(filename: str) -> str:
    """
    Return the matched suffix (e.g. '_d.dds', '_m.dds', '_reg_mask.dds') or '' if none.
    Matches the rightmost occurrence that fits our known suffix patterns.
    """
    low = filename.lower()
    if not low.endswith('.dds'):
        return ""
    
    # Sort by length (longest first) to match '_reg_mask.dds' before '_mask.dds'
    sorted_suffixes = sorted(TEXTURE_SUFFIXES, key=len, reverse=True)
    for suffix in sorted_suffixes:
        if low.endswith(suffix):
            return suffix
    return ""


def get_texture_base_and_suffix(filename: str) -> tuple:
    """
    Split a texture filename into (base, suffix).
    For 'g_tmp_waist_part_05_fur_m.dds' -> ('g_tmp_waist_part_05_fur', '_m.dds')
    For 'g_tmp_waist_part_05_fur_reg_mask.dds' -> ('g_tmp_waist_part_05_fur', '_reg_mask.dds')
    """
    suffix = get_texture_suffix(filename)
    if not suffix:
        return filename, ""
    base = filename[:-len(suffix)]
    return base, suffix


def new_texture_name(old_name: str, new_stem: str) -> tuple:
    """
    Build the new texture filename by replacing the stem before the suffix.
    e.g. old_name='g_res_torso_base_02a_d.dds', new_stem='mymod_top'
         -> 'mymod_top_d.dds'

    Returns (new_name, error_str). error_str is '' on success.
    The new name must be exactly the same byte length as the old one.
    """
    suffix = get_texture_suffix(old_name)
    if not suffix:
        return old_name, ""   # not a targeted texture, keep as-is

    new_name = new_stem + suffix
    if len(new_name.encode("ascii")) != len(old_name.encode("ascii")):
        diff = len(new_name) - len(old_name)
        sign = "+" if diff > 0 else ""
        return new_name, (
            f"'{old_name}' ({len(old_name)} chars)  ->  "
            f"'{new_name}' ({len(new_name)} chars)  [{sign}{diff}]"
        )
    return new_name, ""


def patch_binary_string(data: bytes, old_str: str, new_str: str) -> bytes:
    """
    Replace every null-terminated occurrence of old_str with new_str in binary data.
    new_str must be <= old_str in byte length; remainder is zero-padded.
    Raises ValueError if new_str is longer.
    """
    old_b = old_str.encode("ascii")
    new_b = new_str.encode("ascii")
    if len(new_b) > len(old_b):
        raise ValueError(f"New string longer than old: {new_str!r} > {old_str!r}")
    # Pad to same length with null bytes
    new_b_padded = new_b + b"\x00" * (len(old_b) - len(new_b))

    result = bytearray(data)
    search = old_b
    i = 0
    while True:
        idx = result.find(search, i)
        if idx == -1:
            break
        result[idx:idx + len(old_b)] = new_b_padded
        i = idx + len(old_b)
    return bytes(result)


def patch_mgraphobject(data: bytes, tex_renames: dict) -> bytes:
    """
    Patch a .mgraphobject binary, replacing every DDS path that contains
    a texture we're renaming.

    tex_renames: { old_filename_stem: new_filename_stem }
    e.g. { 'g_res_torso_base_02a_d': 'mymod_top_d' }

    We search for the full filename (with .dds) anywhere in the binary.
    """
    for old_name, new_name in tex_renames.items():
        if old_name == new_name:
            continue
        try:
            data = patch_binary_string(data, old_name, new_name)
        except ValueError as e:
            raise ValueError(f"Cannot patch '{old_name}' -> '{new_name}': {e}")
    return data


# ── Widgets ────────────────────────────────────────────────────────────────────

class FileList(tk.Frame):
    """Searchable, filterable list of .mgraphobject files."""

    def __init__(self, parent, stem_index, on_select=None, **kw):
        super().__init__(parent, bg=BG, **kw)
        self._stem_index = stem_index
        self._on_select  = on_select
        self._all_items  = []
        self._filtered   = []

        # Search bar
        sf = tk.Frame(self, bg=ENTRY_BG, highlightbackground=BORDER, highlightthickness=1)
        sf.pack(fill="x", pady=(0, 5))
        tk.Label(sf, text="⌕", bg=ENTRY_BG, fg=MUTED,
                 font=("Segoe UI", 11)).pack(side="left", padx=(7, 2))
        self._sv = tk.StringVar()
        self._sv.trace_add("write", lambda *_: self._refresh())
        tk.Entry(sf, textvariable=self._sv, bg=ENTRY_BG, fg=TEXT,
                 insertbackground=ACCENT, relief="flat",
                 font=("Segoe UI", 9), bd=0
                 ).pack(side="left", fill="x", expand=True, pady=6, padx=(0, 6))

        # Slot filter + count
        fr = tk.Frame(self, bg=BG)
        fr.pack(fill="x", pady=(0, 5))
        tk.Label(fr, text="Slot:", bg=BG, fg=MUTED, font=("Segoe UI", 9)).pack(side="left")
        self._slot_var = tk.StringVar(value="ALL SLOTS")
        self._slot_cb  = ttk.Combobox(fr, textvariable=self._slot_var,
                                       values=["ALL SLOTS"], state="readonly",
                                       width=12, font=("Segoe UI", 9))
        self._slot_cb.pack(side="left", padx=(5, 0))
        self._slot_cb.bind("<<ComboboxSelected>>", lambda _: self._refresh())
        self._count_var = tk.StringVar()
        tk.Label(fr, textvariable=self._count_var, bg=BG, fg=MUTED,
                 font=("Segoe UI", 8)).pack(side="right")

        # Package filter
        fr2 = tk.Frame(self, bg=BG)
        fr2.pack(fill="x", pady=(0, 5))
        tk.Label(fr2, text="Package:", bg=BG, fg=MUTED, font=("Segoe UI", 9)).pack(side="left")
        self._pkg_var = tk.StringVar(value="ALL PACKAGES")
        self._pkg_cb  = ttk.Combobox(fr2, textvariable=self._pkg_var,
                                      values=["ALL PACKAGES"], state="readonly",
                                      width=14, font=("Segoe UI", 9))
        self._pkg_cb.pack(side="left", padx=(5, 0))
        self._pkg_cb.bind("<<ComboboxSelected>>", lambda _: self._refresh())

        # Text widget used as a coloured listbox (same approach as swap tool)
        wrap = tk.Frame(self, bg=BORDER, highlightbackground=BORDER, highlightthickness=1)
        wrap.pack(fill="both", expand=True)
        sb = tk.Scrollbar(wrap, bg=PANEL, troughcolor=BG, activebackground=ACCENT)
        sb.pack(side="right", fill="y")
        self._lb = tk.Text(wrap, bg=ENTRY_BG, fg=TEXT,
                           relief="flat", bd=0, cursor="arrow",
                           font=("Segoe UI", 9), yscrollcommand=sb.set,
                           highlightthickness=0, state="disabled",
                           spacing1=2, spacing3=2)
        self._lb.pack(side="left", fill="both", expand=True)
        sb.config(command=self._lb.yview)
        self._sel_idx = None
        self._lb.bind("<Button-1>", self._on_click)
        self._lb.bind("<Button-3>", self._on_right_click)
        self._lb.bind("<MouseWheel>", lambda e: self._lb.yview_scroll(int(-1*(e.delta/120)), "units"))

        # Right-click context menu
        self._ctx_menu = tk.Menu(self, tearoff=0, bg=PANEL, fg=TEXT,
                                  activebackground=BTN_BG, activeforeground=ACCENT,
                                  font=("Segoe UI", 9), relief="flat", bd=1)

    def load(self, paths: list):
        slots_seen = set()
        pkgs_seen  = set()
        items = []
        for p in sorted(paths, key=lambda x: x.stem.lower()):
            stem  = p.stem.lower()
            entry = self._stem_index.get(stem, {})
            slot  = entry.get("slot", "Custom").upper()
            pkg   = entry.get("package", "custom")
            slots_seen.add(slot)
            pkgs_seen.add(pkg)
            items.append({
                "path":         p,
                "stem":         p.stem,
                "filename":     p.name,
                "slot":         slot,
                "package":      pkg,
                "ui_names":     entry.get("ui_names", []),
                "textures":     [],
                "models":       entry.get("models", []),
                "mgraphobject": entry.get("mgraphobject", []),
            })
        self._all_items = items
        slots = ["ALL SLOTS"] + sorted(s.upper() for s in slots_seen)
        self._slot_cb.config(values=slots)
        self._slot_var.set("ALL SLOTS")
        pkgs = ["ALL PACKAGES"] + sorted(pkgs_seen)
        self._pkg_cb.config(values=pkgs)
        self._pkg_var.set("ALL PACKAGES")
        self._refresh()

    def _refresh(self):
        q    = self._sv.get().strip().lower()
        slot = self._slot_var.get()
        pkg  = self._pkg_var.get()
        self._filtered = [
            i for i in self._all_items
            if (slot == "ALL SLOTS" or i["slot"] == slot)
            and (pkg == "ALL PACKAGES" or i["package"] == pkg)
            and (not q
                 or q in i["stem"].lower()
                 or any(q in n.lower() for n in i["ui_names"]))
        ]
        self._sel_idx = None
        self._lb.config(state="normal")
        self._lb.delete("1.0", "end")

        for item in self._filtered:
            t     = item["slot"].lower()
            p     = item["package"]
            t_tag = f"type_{t}"
            p_tag = f"pkg_{p}"
            self._lb.tag_config(t_tag, foreground=TYPE_COLORS.get(t, TYPE_COLOR_DEFAULT),
                                font=("Segoe UI", 9, "bold"))
            self._lb.tag_config(p_tag, foreground=PKG_COLORS.get(p, PKG_COLOR_DEFAULT),
                                font=("Segoe UI", 9, "bold"))
            self._lb.tag_config("name", foreground=TEXT, font=("Segoe UI", 9))
            self._lb.tag_config("custom_tag", foreground=WARN, font=("Segoe UI", 9))
            self._lb.insert("end", f"[{item['slot'].upper()}]", t_tag)
            self._lb.insert("end", "  ")
            self._lb.insert("end", f"[{p}]", p_tag)
            self._lb.insert("end", "  ")
            if item["ui_names"]:
                self._lb.insert("end", item["ui_names"][0] + "  ", "name")
                self._lb.insert("end", f"({item['stem']})\n", "custom_tag")
            else:
                self._lb.insert("end", f"({item['stem']})\n", "custom_tag")

        self._lb.config(state="disabled")
        self._count_var.set(f"{len(self._filtered)} files")

    def _on_click(self, event):
        index    = self._lb.index(f"@{event.x},{event.y}")
        line_num = int(index.split(".")[0]) - 1  # 0-based
        if 0 <= line_num < len(self._filtered):
            self._sel_idx = line_num
            self._highlight_selected()
            if self._on_select:
                self._on_select(self._filtered[line_num])

    def _highlight_selected(self):
        self._lb.tag_delete("selected_row")
        if self._sel_idx is not None:
            line = self._sel_idx + 1
            self._lb.tag_add("selected_row", f"{line}.0", f"{line}.end")
            self._lb.tag_config("selected_row", background=BTN_BG)

    def _on_right_click(self, event):
        index    = self._lb.index(f"@{event.x},{event.y}")
        line_num = int(index.split(".")[0]) - 1
        if not (0 <= line_num < len(self._filtered)):
            return
        item = self._filtered[line_num]
        self._ctx_menu.delete(0, "end")
        self._ctx_menu.add_command(
            label=f"Copy stem:  {item['stem']}",
            command=lambda: self._copy_filename(item["stem"]))
        try:
            self._ctx_menu.tk_popup(event.x_root, event.y_root)
        finally:
            self._ctx_menu.grab_release()

    def _copy_filename(self, name):
        self.clipboard_clear()
        self.clipboard_append(name)
        self.update()

    def get_selected(self):
        if self._sel_idx is not None and self._sel_idx < len(self._filtered):
            return self._filtered[self._sel_idx]
        return None

    def clear(self):
        self._all_items = []
        self._filtered  = []
        self._sel_idx   = None
        self._lb.config(state="normal")
        self._lb.delete("1.0", "end")
        self._lb.config(state="disabled")
        self._count_var.set("")


class InfoCard(tk.Frame):
    """Detail panel for a selected .mgraphobject entry."""

    def __init__(self, parent, title, title_color, **kw):
        super().__init__(parent, bg=PANEL, highlightbackground=BORDER,
                         highlightthickness=1, **kw)
        hdr = tk.Frame(self, bg=PANEL)
        hdr.pack(fill="x", padx=10, pady=(8, 4))
        tk.Label(hdr, text=title, bg=PANEL, fg=title_color,
                 font=("Segoe UI", 9, "bold")).pack(side="left")
        self._slot_lbl = tk.Label(hdr, text="", bg=PANEL, fg=MUTED,
                                   font=("Segoe UI", 8))
        self._slot_lbl.pack(side="right")
        tk.Frame(self, bg=BORDER, height=1).pack(fill="x")
        self._text = tk.Text(self, bg=PANEL, fg=TEXT, relief="flat",
                              font=(MONO, 10), bd=0, state="disabled",
                              wrap="word", padx=10, pady=8,
                              highlightthickness=0, width=1, height=1)
        self._text.pack(fill="both", expand=True)
        self._text.tag_config("key",     foreground=MUTED)
        self._text.tag_config("val",     foreground=TEXT)
        self._text.tag_config("acc",     foreground=ACCENT,  font=(MONO, 10, "bold"))
        self._text.tag_config("acc2",    foreground=ACCENT2)
        self._text.tag_config("warn",    foreground=WARN)
        self._text.tag_config("found",   foreground=SUCCESS)
        self._text.tag_config("missing", foreground=ERROR)
        self._text.tag_config("muted",   foreground=MUTED,   font=(MONO, 9))
        self.clear()

    def clear(self):
        self._slot_lbl.config(text="")
        self._write([("key", "No file selected.")])

    def show(self, item: dict, texture_results: dict = None):
        pkg = item.get("package", "")
        self._slot_lbl.config(text=f"{item['slot']}  ·  {pkg}" if pkg else item["slot"])
        lines = [("key", "File:\n"), ("acc", f"  {item['filename']}\n")]
        if item["ui_names"]:
            lines += [("key", "\nKnown as:\n")]
            for n in item["ui_names"]:
                lines += [("val", f"  {n}\n")]
        else:
            lines += [("key", "\n"), ("warn", "  Custom file - not in gear index.\n")]

        tex_source = item.get("tex_source")  # "binary", "default", or None (scanning)

        if texture_results is None:
            # Still scanning
            lines += [("key", "\n"), ("warn", "  Scanning for textures...\n")]
        elif not item["textures"]:
            lines += [("key", "\n"), ("muted", "  No textures found.\n")]
        else:
            if tex_source == "binary":
                lines += [("key", "\nTextures  "), ("muted", "(read from graph file):\n")]
            elif tex_source == "default":
                lines += [("key", "\nTextures  "), ("muted", "(guessed from filename):\n")]
            else:
                lines += [("key", "\nTextures:\n")]

            for t in item["textures"]:
                if texture_results.get(t):
                    lines += [("found", f"  {t}\n")]
                else:
                    lines += [("missing", f"  {t}\n")]

            found = sum(1 for v in texture_results.values() if v)
            total = len(texture_results)
            tag   = "found" if found == total else ("warn" if found else "missing")
            lines += [("key", "\n"), (tag, f"  {found}/{total} found\n")]

        self._write(lines)

    def _write(self, segs):
        self._text.config(state="normal")
        self._text.delete("1.0", "end")
        for tag, txt in segs:
            self._text.insert("end", txt, tag)
        self._text.config(state="disabled")


# ── Main App ───────────────────────────────────────────────────────────────────

class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("AFoP Texture Redirector | Made By: Jasper_Zebra | Version 2.6")
        self.geometry("1400x1000")
        self.minsize(1000, 640)
        self.configure(bg=BG)

        style = ttk.Style(self)
        style.theme_use("clam")
        style.configure("TCombobox",
                         fieldbackground=ENTRY_BG, background=ENTRY_BG,
                         foreground=TEXT, selectbackground=BTN_BG,
                         selectforeground=ACCENT, bordercolor=BORDER,
                         arrowcolor=ACCENT, relief="flat")
        style.map("TCombobox", fieldbackground=[("readonly", ENTRY_BG)])

        self._all_data        = load_all_json_data()
        self._stem_index      = build_stem_index(self._all_data)
        self._prefs           = load_prefs()
        self._sel_res         = None
        self._sel_mod         = None
        self._texture_results = {}
        self._gear_swap_only  = tk.BooleanVar(value=False)
        self._tex_unlinked    = set()   # textures the user has manually unlinked
        
        # Undo/redo stacks for the new graph name entry
        self._undo_stack      = []
        self._redo_stack      = []
        self._last_value      = ""
        self._undo_in_progress = False

        self._build_ui()
        self._auto_restore()

    # ── UI ─────────────────────────────────────────────────────────────────────

    def _build_ui(self):
        # Title bar
        bar = tk.Frame(self, bg=PANEL, height=48)
        bar.pack(fill="x")
        bar.pack_propagate(False)
        tk.Label(bar, text="TEXTURE REDIRECTOR",
                 bg=PANEL, fg=ACCENT, font=(MONO, 13, "bold"),
                 padx=16).pack(side="left", fill="y")
        tk.Label(bar, text="Avatar: Frontiers of Pandora  ·  texture mod utility",
                 bg=PANEL, fg=MUTED, font=("Segoe UI", 9)
                 ).pack(side="left", fill="y")
        tk.Frame(self, bg=BORDER, height=1).pack(fill="x")

        # Path rows
        self._res_var = tk.StringVar(value=self._prefs.get("resource_folder", ""))
        self._mod_var = tk.StringVar(value=self._prefs.get("mod_folder", ""))
        self._make_path_row("Resource folder  (game files root):",
                             self._res_var, self._browse_resource)
        self._make_path_row("Mod output folder:",
                             self._mod_var, self._browse_mod)
        tk.Frame(self, bg=BORDER, height=1).pack(fill="x")

        # Main body
        main = tk.Frame(self, bg=BG)
        main.pack(fill="both", expand=True)

        # ── Left: resource files
        left = tk.Frame(main, bg=BG)
        left.pack(side="left", fill="both", expand=True, padx=(12, 6), pady=12)

        lhdr = tk.Frame(left, bg=BG)
        lhdr.pack(fill="x", pady=(0, 6))
        tk.Label(lhdr, text="RESOURCE FOLDER",
                 bg=BG, fg=ACCENT,
                 font=("Segoe UI", 9, "bold")).pack(side="left")
        self._res_badge = tk.Label(lhdr, text="Not scanned",
                                    bg=BG, fg=MUTED, font=("Segoe UI", 8))
        self._res_badge.pack(side="right")

        self._res_list = FileList(left, self._stem_index,
                                   on_select=self._on_res_select)
        self._res_list.pack(fill="both", expand=True)

        tk.Frame(main, bg=BORDER, width=1).pack(side="left", fill="y", pady=12)

        # ── Centre: cards + rename + actions
        mid = tk.Frame(main, bg=BG, width=420)
        mid.pack(side="left", fill="both", padx=6, pady=12)
        mid.pack_propagate(False)

        # Draggable split between the info card and the rename panel
        mid_pane = tk.PanedWindow(mid, orient="vertical", bg=BORDER,
                                   sashwidth=5, sashrelief="flat",
                                   sashpad=0, opaqueresize=True)
        mid_pane.pack(fill="both", expand=True, pady=(0, 6))

        self._res_card = InfoCard(mid_pane, "RESOURCE FILE", ACCENT)
        mid_pane.add(self._res_card, stretch="always", minsize=80)

        # ── Rename panel
        rename_frame = tk.Frame(mid_pane, bg=PANEL, highlightbackground=BORDER,
                                 highlightthickness=1)
        mid_pane.add(rename_frame, stretch="always", minsize=110)
        mid_pane.after(100, lambda: mid_pane.sash_place(0, 0, mid_pane.winfo_height() // 2 + 200))

        rename_hdr = tk.Frame(rename_frame, bg=PANEL)
        rename_hdr.pack(fill="x", padx=10, pady=(8, 4))
        tk.Label(rename_hdr, text="NEW GRAPH FILE NAME", bg=PANEL, fg=WARN,
                 font=("Segoe UI", 9, "bold")).pack(side="left")
        self._mg_len_lbl = tk.Label(rename_hdr, text="", bg=PANEL, fg=MUTED,
                                     font=(MONO, 8))
        self._mg_len_lbl.pack(side="right")

        tk.Frame(rename_frame, bg=BORDER, height=1).pack(fill="x")

        entry_row = tk.Frame(rename_frame, bg=PANEL)
        entry_row.pack(fill="x", padx=10, pady=(8, 4))
        self._new_mg_var = tk.StringVar()
        self._new_mg_var.trace_add("write", self._on_mg_name_change)
        self._mg_entry = tk.Entry(entry_row, textvariable=self._new_mg_var,
                 bg=ENTRY_BG, fg=TEXT,
                 insertbackground=ACCENT, relief="flat",
                 font=(MONO, 10), bd=4
                 )
        self._mg_entry.pack(fill="x")
        
        # Bind Ctrl+Z (undo) and Ctrl+Y (redo) for the entry field
        self._mg_entry.bind("<Control-z>", self._undo)
        self._mg_entry.bind("<Control-y>", self._redo)
        # Also bind Ctrl+Shift+Z as alternative redo
        self._mg_entry.bind("<Control-Shift-Z>", self._redo)

        # Gear swap only checkbox
        swap_row = tk.Frame(rename_frame, bg=PANEL)
        swap_row.pack(fill="x", padx=10, pady=(4, 0))
        tk.Checkbutton(swap_row, text="Gear swap only (rename file only)",
                       variable=self._gear_swap_only,
                       bg=PANEL, fg=MUTED, selectcolor=ENTRY_BG,
                       activebackground=PANEL, activeforeground=TEXT,
                       font=("Segoe UI", 8),
                       command=self._on_mg_name_change
                       ).pack(side="left")

        # Slot mismatch warning
        self._slot_warn_lbl = tk.Label(rename_frame, text="", bg=PANEL, fg=WARN,
                                       font=("Segoe UI", 8), anchor="w", padx=10,
                                       justify="left", wraplength=360)
        self._slot_warn_lbl.bind("<Configure>", lambda e: self._slot_warn_lbl.config(wraplength=e.width - 20))
        self._slot_warn_lbl.pack(fill="x")

        # Derived texture names preview -- scrollable, fills remaining space
        tk.Frame(rename_frame, bg=BORDER, height=1).pack(fill="x", pady=(4, 0))
        tex_hdr = tk.Frame(rename_frame, bg=PANEL)
        tex_hdr.pack(fill="x", padx=10, pady=(6, 2))
        tk.Label(tex_hdr, text="DERIVED TEXTURE NAMES", bg=PANEL, fg=MUTED,
                 font=("Segoe UI", 8, "bold")).pack(side="left")
        self._tex_len_lbl = tk.Label(tex_hdr, text="", bg=PANEL, fg=MUTED,
                                      font=(MONO, 8))
        self._tex_len_lbl.pack(side="right")

        self._tex_check_vars  = {}   # old_tex_name -> BooleanVar

        # Scrollable container for derived texture rows (no visible scrollbar — mousewheel only)
        tex_canvas = tk.Canvas(rename_frame, bg=PANEL, highlightthickness=0, bd=0)
        tex_canvas.pack(fill="both", expand=True, padx=10, pady=(0, 8))

        self._tex_check_frame = tk.Frame(tex_canvas, bg=PANEL)
        self._tex_canvas_window = tex_canvas.create_window(
            (0, 0), window=self._tex_check_frame, anchor="nw")

        def _on_tex_frame_configure(event):
            tex_canvas.configure(scrollregion=tex_canvas.bbox("all"))

        def _on_tex_canvas_resize(event):
            tex_canvas.itemconfig(self._tex_canvas_window, width=event.width)

        self._tex_check_frame.bind("<Configure>", _on_tex_frame_configure)
        tex_canvas.bind("<Configure>", _on_tex_canvas_resize)

        def _on_tex_mousewheel(event):
            tex_canvas.yview_scroll(int(-1 * (event.delta / 120)), "units")

        tex_canvas.bind("<MouseWheel>", _on_tex_mousewheel)
        self._tex_check_frame.bind("<MouseWheel>", _on_tex_mousewheel)

        # ── Buttons
        tk.Button(mid, text="⤓  COPY & RENAME TO MOD FOLDER",
                  bg=BTN_BG, fg=ACCENT,
                  activebackground=BTN_HOV, activeforeground=ACCENT,
                  relief="flat", font=(MONO, 10, "bold"),
                  cursor="hand2", pady=10,
                  command=self._copy_to_mod
                  ).pack(fill="x", pady=(0, 4))

        tk.Button(mid, text="↺  Refresh panels",
                  bg=PANEL, fg=MUTED,
                  activebackground=BTN_HOV, activeforeground=TEXT,
                  relief="flat", font=("Segoe UI", 8),
                  cursor="hand2", pady=6,
                  command=self._refresh_both
                  ).pack(fill="x")

        tk.Frame(main, bg=BORDER, width=1).pack(side="left", fill="y", pady=12)

        # ── Right: mod files
        right = tk.Frame(main, bg=BG)
        right.pack(side="left", fill="both", expand=True, padx=(6, 12), pady=12)

        rhdr = tk.Frame(right, bg=BG)
        rhdr.pack(fill="x", pady=(0, 6))
        tk.Label(rhdr, text="MOD FOLDER",
                 bg=BG, fg=SUCCESS,
                 font=("Segoe UI", 9, "bold")).pack(side="left")
        self._mod_badge = tk.Label(rhdr, text="Not set",
                                    bg=BG, fg=MUTED, font=("Segoe UI", 8))
        self._mod_badge.pack(side="right")

        self._mod_list = FileList(right, self._stem_index,
                                   on_select=self._on_mod_select)
        self._mod_list.pack(fill="both", expand=True)

        # Status bar
        tk.Frame(self, bg=BORDER, height=1).pack(fill="x")
        self._status_var = tk.StringVar(value="Set your resource and mod folders to begin.")
        self._status_lbl = tk.Label(self, textvariable=self._status_var,
                                     bg=PANEL, fg=MUTED,
                                     font=("Segoe UI", 8), anchor="w",
                                     padx=12, pady=5)
        self._status_lbl.pack(fill="x")

    def _make_path_row(self, label, var, cmd):
        row = tk.Frame(self, bg=PANEL, height=42)
        row.pack(fill="x")
        row.pack_propagate(False)
        tk.Label(row, text=label, bg=PANEL, fg=MUTED,
                 font=("Segoe UI", 9), padx=12).pack(side="left", fill="y")
        tk.Entry(row, textvariable=var, bg=ENTRY_BG, fg=TEXT,
                 insertbackground=ACCENT, relief="flat",
                 font=(MONO, 8), bd=4
                 ).pack(side="left", fill="both", expand=True, pady=7)
        tk.Button(row, text="Browse...", bg=BTN_BG, fg=TEXT,
                  activebackground=BTN_HOV, activeforeground=ACCENT,
                  relief="flat", font=("Segoe UI", 9), padx=10,
                  cursor="hand2", command=cmd
                  ).pack(side="left", padx=(6, 12), pady=7)

    # ── Stem change / validation ───────────────────────────────────────────────

    def _derive_texture_names(self, new_mg_stem: str) -> list:
        """
        Given a new graph file stem, derive new texture filenames.

        Strategy:
        - Strip gender suffixes (_f, _m) from both graph stems to get the "core" name
        - For each texture, check if it starts with the old graph core
        - If related: replace the matching prefix with new graph core, keep remainder
          (e.g., 'g_res_torso_base_02a' with '02' -> '03' becomes 'g_res_torso_base_03a')
        - If unrelated (like dn_cotton01_n.dds): keep unchanged
        
        This properly handles cases where:
          - Graph: g_res_torso_base_02_f -> g_res_torso_base_03_f
          - Texture: g_res_torso_base_02a_d.dds -> g_res_torso_base_03a_d.dds
        
        Returns list of (old_tex_name, new_tex_name) for all textures.
        """
        item = self._sel_res
        if not item:
            return []
        old_mg_stem  = item["path"].stem
        all_textures = item.get("textures", [])
        if not all_textures:
            return []

        # Strip gender suffix from graph stems (_f, _m) for comparison
        old_mg_core = old_mg_stem.rstrip('_fm')
        if old_mg_core and old_mg_core[-1] == '_':
            old_mg_core = old_mg_core[:-1]
        
        new_mg_core = new_mg_stem.rstrip('_fm')
        if new_mg_core and new_mg_core[-1] == '_':
            new_mg_core = new_mg_core[:-1]

        pairs = []
        for t in all_textures:
            suffix = get_texture_suffix(t)

            if not suffix:
                # Not a targeted texture type — always keep as-is
                pairs.append((t, t, False))
                continue

            tex_stem = t[:-len(suffix)]

            # Check if texture stem starts with the old graph core
            if tex_stem.lower().startswith(old_mg_core.lower()):
                # Texture is related - replace the matching prefix with the new one
                remainder = tex_stem[len(old_mg_core):]  # Keep suffixes like 'a', 'b', '01', etc.
                new_tex_stem = new_mg_core + remainder
                new_tex_name = new_tex_stem + suffix
                is_linked = True
            else:
                # Unrelated / generic texture (like dn_cotton01_n.dds) - keep unchanged
                new_tex_name = t
                is_linked = False

            pairs.append((t, new_tex_name, is_linked))
        return pairs

    def _on_mg_name_change(self, *_):
        """Live-validate new graph name and rebuild read-only derived texture rows."""
        new_mg = self._new_mg_var.get().strip()
        item   = self._sel_res
        
        # Track undo/redo history (skip if we're doing undo/redo to avoid recursion)
        if not self._undo_in_progress:
            current_value = self._new_mg_var.get()
            if current_value != self._last_value:
                self._undo_stack.append(self._last_value)
                self._last_value = current_value
                self._redo_stack.clear()  # Clear redo stack on new changes

        # Strip extension if the user typed it in
        if new_mg.lower().endswith(".mgraphobject"):
            new_mg = new_mg[: -len(".mgraphobject")]

        # Clear existing rows and checkbox state
        for w in self._tex_check_frame.winfo_children():
            w.destroy()
        self._tex_check_vars = {}   # old_tex_name -> BooleanVar (auto-derive from graph name)
        self._tex_manual_vars = {}  # old_tex_name -> BooleanVar (manual naming)
        self._tex_manual_entries = {}  # old_tex_name -> Entry widget
        self._tex_manual_names = {}  # old_tex_name -> StringVar (manual name storage)

        if not item or not new_mg:
            self._mg_len_lbl.config(text="")
            self._tex_len_lbl.config(text="")
            self._slot_warn_lbl.config(text="")
            return

        old_mg    = item["path"].stem
        gear_swap = self._gear_swap_only.get()

        # ── Slot mismatch warning
        new_entry = self._stem_index.get(new_mg.lower())
        if new_mg.lower() != old_mg.lower() and new_entry and new_entry.get("slot") and new_entry["slot"] != item["slot"]:
            self._slot_warn_lbl.config(
                text=f"⚠  Slot mismatch: source is '{item['slot']}', target is '{new_entry['slot']}' — may not display correctly or might crash in-game.")
        else:
            self._slot_warn_lbl.config(text="")

        if gear_swap:
            self._mg_len_lbl.config(text=f"{len(new_mg)} chars  ✓", fg=SUCCESS)
            self._tex_len_lbl.config(text="skipped", fg=MUTED)
            tk.Label(self._tex_check_frame,
                     text="  (gear swap only — DDS files unchanged)",
                     bg=PANEL, fg=MUTED, font=("Segoe UI", 8)).pack(anchor="w")
            return

        # ── Graph name length indicator
        diff = len(new_mg) - len(old_mg)
        sign = "+" if diff > 0 else ""
        self._mg_len_lbl.config(
            text=f"{len(new_mg)} chars  ({sign}{diff})" if diff != 0 else f"{len(new_mg)} chars  ✓",
            fg=ERROR if diff != 0 else SUCCESS)

        pairs = self._derive_texture_names(new_mg)

        # ── Table layout for texture rows using grid
        # Columns: 0=linked_cb, 1=edit_cb, 2=stem_entry, 3=suffix, 4=diff_badge
        COL_CB1    = 0
        COL_CB2    = 1
        COL_STEM   = 2
        COL_SUFFIX = 3
        COL_DIFF   = 4

        HIGHLIGHT_BG = "#2a3550"

        if pairs:
            # Header row
            tk.Label(self._tex_check_frame, text="linked", bg=PANEL, fg=MUTED,
                     font=("Segoe UI", 7)).grid(row=0, column=COL_CB1, sticky="w", padx=(2,0), pady=(0,2))
            tk.Label(self._tex_check_frame, text="edit", bg=PANEL, fg=MUTED,
                     font=("Segoe UI", 7)).grid(row=0, column=COL_CB2, sticky="w", padx=(2,0), pady=(0,2))
            tk.Label(self._tex_check_frame, text="texture name", bg=PANEL, fg=MUTED,
                     font=("Segoe UI", 7)).grid(row=0, column=COL_STEM, sticky="w", padx=(4,0), pady=(0,2))
            tk.Label(self._tex_check_frame, text="suffix", bg=PANEL, fg=MUTED,
                     font=("Segoe UI", 7)).grid(row=0, column=COL_SUFFIX, sticky="w", padx=(2,0), pady=(0,2))
            # Make stem column expandable
            self._tex_check_frame.columnconfigure(COL_STEM, weight=1)

        for row_idx, (old_t, new_t, is_linked) in enumerate(pairs, start=1):
            suffix    = get_texture_suffix(old_t)
            unchanged = (old_t == new_t)
            has_err   = bool(suffix) and (len(new_t) - len(suffix) != len(old_t) - len(suffix))
            new_stem  = new_t[: -len(suffix)] if suffix else new_t
            old_stem  = old_t[: -len(suffix)] if suffix else old_t

            was_unlinked = old_t in self._tex_unlinked
            check_var = tk.BooleanVar(value=is_linked and not unchanged and not was_unlinked)
            manual_var = tk.BooleanVar(value=False)
            manual_name_var = tk.StringVar(value=old_stem if (unchanged or was_unlinked) else new_stem)

            self._tex_check_vars[old_t] = check_var
            self._tex_manual_vars[old_t] = manual_var
            self._tex_manual_names[old_t] = manual_name_var

            # Stem colour: error=red, ok=accent2, unchanged/unlinked=muted
            stem_fg = MUTED if (unchanged or was_unlinked) else (ERROR if has_err else ACCENT2)
            init_bg = HIGHLIGHT_BG if (is_linked and not unchanged and not was_unlinked) else PANEL

            # ── First checkbox
            def _make_auto_toggle(cv, mv, stem_entry, on_fg, new_stem_text, old_stem_text, diff_lbl, tex_name):
                def _toggle():
                    if cv.get():
                        self._tex_unlinked.discard(tex_name)
                        mv.set(False)
                        stem_entry.config(state="normal")
                        stem_entry.delete(0, tk.END)
                        stem_entry.insert(0, new_stem_text)
                        stem_entry.config(state="readonly", readonlybackground=HIGHLIGHT_BG, fg=on_fg)
                        if diff_lbl:
                            diff_lbl.grid()
                    else:
                        self._tex_unlinked.add(tex_name)
                        stem_entry.config(state="normal")
                        stem_entry.delete(0, tk.END)
                        stem_entry.insert(0, old_stem_text)
                        stem_entry.config(state="readonly", fg=MUTED, readonlybackground=PANEL)
                        if diff_lbl:
                            diff_lbl.grid_remove()
                    self._update_tex_len_lbl()
                return _toggle

            def _make_manual_toggle(cv, mv, stem_entry, manual_name_var_inner, on_fg):
                def _toggle():
                    if mv.get():
                        cv.set(False)
                        stem_entry.config(state="normal", bg=HIGHLIGHT_BG, fg=on_fg)
                        stem_entry.focus_set()
                        stem_entry.icursor(tk.END)
                        manual_name_var_inner.set(stem_entry.get())
                    else:
                        stem_entry.config(state="readonly", readonlybackground=PANEL, bg=PANEL, fg=MUTED)
                    self._update_tex_len_lbl()
                return _toggle

            # Only show the linked checkbox for textures related to the mgraph
            if is_linked:
                cb_auto = tk.Checkbutton(self._tex_check_frame, variable=check_var,
                                    bg=PANEL, fg=MUTED, selectcolor=ENTRY_BG,
                                    activebackground=PANEL, activeforeground=TEXT,
                                    relief="flat", bd=0, highlightthickness=0, cursor="hand2")
                cb_auto.grid(row=row_idx, column=COL_CB1, sticky="w", padx=(2,0), pady=1)
            else:
                # Placeholder so grid column stays aligned
                tk.Label(self._tex_check_frame, bg=PANEL, width=2).grid(
                    row=row_idx, column=COL_CB1, sticky="w", padx=(2,0), pady=1)

            cb_manual = tk.Checkbutton(self._tex_check_frame, variable=manual_var,
                                bg=PANEL, fg=MUTED, selectcolor=ENTRY_BG,
                                activebackground=PANEL, activeforeground=TEXT,
                                relief="flat", bd=0, highlightthickness=0, cursor="hand2")
            cb_manual.grid(row=row_idx, column=COL_CB2, sticky="w", padx=(2,0), pady=1)

            stem_entry = tk.Entry(self._tex_check_frame, textvariable=manual_name_var,
                                 bg=PANEL, fg=stem_fg, font=(MONO, 8),
                                 relief="flat", bd=2, state="readonly",
                                 width=28, insertbackground=TEXT,
                                 readonlybackground=init_bg, disabledbackground=PANEL)
            stem_entry.grid(row=row_idx, column=COL_STEM, sticky="ew", padx=(4,0), pady=1)
            self._tex_manual_entries[old_t] = stem_entry

            manual_name_var.trace_add("write", lambda *args, ot=old_t: self._validate_manual_name(ot))

            suffix_lbl = tk.Label(self._tex_check_frame, text=suffix, bg=PANEL, fg=MUTED,
                                  font=(MONO, 8), anchor="w")
            suffix_lbl.grid(row=row_idx, column=COL_SUFFIX, sticky="w", padx=(2,8), pady=1)

            old_stem_len = len(old_t) - len(suffix)
            new_stem_len = len(new_t) - len(suffix)
            diff_lbl = None
            if new_stem_len != old_stem_len:
                tdiff = new_stem_len - old_stem_len
                tsign = "+" if tdiff > 0 else ""
                diff_lbl = tk.Label(self._tex_check_frame, text=f"{tsign}{tdiff}", bg=PANEL, fg=ERROR,
                                    font=(MONO, 8))
                diff_lbl.grid(row=row_idx, column=COL_DIFF, sticky="w", padx=(0,4), pady=1)
                if was_unlinked:
                    diff_lbl.grid_remove()

            if is_linked:
                cb_auto.config(command=_make_auto_toggle(check_var, manual_var, stem_entry, stem_fg, new_stem, old_stem, diff_lbl, old_t))
            cb_manual.config(command=_make_manual_toggle(check_var, manual_var, stem_entry, manual_name_var, stem_fg))

        # Bind mousewheel to every child widget so scrolling works anywhere in the section
        def _bind_mousewheel(widget):
            widget.bind("<MouseWheel>", lambda e: self._tex_check_frame.master.yview_scroll(
                int(-1 * (e.delta / 120)), "units"))
            for child in widget.winfo_children():
                _bind_mousewheel(child)
        _bind_mousewheel(self._tex_check_frame)

        self._update_tex_len_lbl()

    def _validate_manual_name(self, old_tex):
        """Validate manual texture name length matches original."""
        if old_tex not in self._tex_manual_entries:
            return
        
        entry = self._tex_manual_entries[old_tex]
        manual_name = entry.get().strip()
        suffix = get_texture_suffix(old_tex)
        old_stem = old_tex[: -len(suffix)] if suffix else old_tex
        
        # Only validate if manual mode is active
        if not self._tex_manual_vars.get(old_tex, tk.BooleanVar(value=False)).get():
            return
        
        # Check length
        if len(manual_name) == len(old_stem):
            entry.config(fg=ACCENT2)
        elif len(manual_name) == 0:
            entry.config(fg=TEXT)  # Empty is neutral
        else:
            entry.config(fg=ERROR)
        
        self._update_tex_len_lbl()

    def _update_tex_len_lbl(self):
        """Recount length errors for currently enabled textures and update the label."""
        if not self._sel_res:
            return
        new_mg = self._new_mg_var.get().strip()
        if new_mg.lower().endswith(".mgraphobject"):
            new_mg = new_mg[: -len(".mgraphobject")]
        if not new_mg:
            self._tex_len_lbl.config(text="")
            return
        
        pairs = self._derive_texture_names(new_mg)
        err_count  = 0
        active_count = 0

        for old_t, new_t, _ in pairs:
            suffix = get_texture_suffix(old_t)
            if not suffix:  # skip non-targeted textures
                continue

            old_stem = old_t[: -len(suffix)]

            # Check if auto checkbox is enabled
            if self._tex_check_vars.get(old_t, tk.BooleanVar(value=False)).get():
                active_count += 1
                new_stem = new_t[: -len(suffix)]
                if len(new_stem) != len(old_stem):
                    err_count += 1

            # Check if manual checkbox is enabled
            elif self._tex_manual_vars.get(old_t, tk.BooleanVar(value=False)).get():
                active_count += 1
                entry = self._tex_manual_entries.get(old_t)
                if entry:
                    manual_stem = entry.get().strip()
                    if manual_stem and len(manual_stem) != len(old_stem):
                        err_count += 1

        if active_count == 0:
            self._tex_len_lbl.config(text="", fg=MUTED)
        else:
            self._tex_len_lbl.config(
                text=f"{err_count} length error(s)" if err_count else "✓ all match",
                fg=ERROR if err_count else SUCCESS)

    # ── Folder browsing ────────────────────────────────────────────────────────

    def _browse_resource(self):
        d = filedialog.askdirectory(title="Select Game Resource Folder",
                                     initialdir=self._res_var.get() or None)
        if d:
            self._res_var.set(d)
            self._prefs["resource_folder"] = d
            save_prefs(self._prefs)
            self._scan_resource(d)

    def _browse_mod(self):
        d = filedialog.askdirectory(title="Select Mod Output Folder",
                                     initialdir=self._mod_var.get() or None)
        if d:
            self._mod_var.set(d)
            self._prefs["mod_folder"] = d
            save_prefs(self._prefs)
            self._scan_mod(d)

    # ── Scanning ───────────────────────────────────────────────────────────────

    def _auto_restore(self):
        res = self._res_var.get().strip()
        mod = self._mod_var.get().strip()
        if res and os.path.isdir(res):
            self._scan_resource(res)
        if mod and os.path.isdir(mod):
            self._scan_mod(mod)

    def _scan_resource(self, folder):
        self._res_badge.config(text="Scanning...", fg=WARN)
        self._set_status("Scanning resource folder...")
        def worker():
            paths = scan_folder(folder)
            self.after(0, self._finish_resource_scan, paths)
        threading.Thread(target=worker, daemon=True).start()

    def _finish_resource_scan(self, paths):
        self._res_list.load(paths)
        n = len(paths)
        self._res_badge.config(
            text=f"{n} file{'s' if n != 1 else ''} found",
            fg=SUCCESS if n else WARN)
        self._set_status(
            f"Resource folder scanned -- {n} .mgraphobject file(s) found.",
            color=SUCCESS if n else WARN)

    def _scan_mod(self, folder):
        self._mod_badge.config(text="Scanning...", fg=WARN)
        def worker():
            paths = scan_folder(folder)
            self.after(0, self._finish_mod_scan, paths)
        threading.Thread(target=worker, daemon=True).start()

    def _finish_mod_scan(self, paths):
        self._mod_list.load(paths)
        n = len(paths)
        self._mod_badge.config(
            text=f"{n} file{'s' if n != 1 else ''}" if n else "Empty",
            fg=SUCCESS if n else MUTED)

    def _refresh_both(self):
        res = self._res_var.get().strip()
        mod = self._mod_var.get().strip()
        if res and os.path.isdir(res):
            self._scan_resource(res)
        if mod and os.path.isdir(mod):
            self._scan_mod(mod)

    # ── Selection callbacks ────────────────────────────────────────────────────

    def _on_res_select(self, item):
        self._sel_res         = item
        self._texture_results = {}
        self._res_card.show(item, texture_results=None)
        self._set_status(
            f"Resource: {item['filename']}  [{item['slot']}]  -- searching textures...")
        # Pre-fill with the current graph file stem
        # Pre-fill with the current graph file stem — done AFTER texture scan in _on_texture_search_done
        res = self._res_var.get().strip()

        # For both CUSTOM and known items: extract DDS refs from the binary itself.
        # This ensures the texture list always reflects what's actually embedded in
        # the file, rather than relying solely on the JSON which may be incomplete.
        def worker():
            dds_data = extract_dds_from_binary(item["path"])  # [(full_path, filename), ...]
            # Last resort: if still no targeted textures found anywhere, synthesise the
            # four standard names from the graph file's own stem so the user has
            # something sensible to work with (_d, _n, _m, _reg_mask).
            targeted = [fname for full_path, fname in dds_data if is_targeted_texture(fname)]
            if not targeted:
                stem = item["path"].stem
                dds_data = [
                    (f"textures/{stem}_d.dds", f"{stem}_d.dds"),
                    (f"textures/{stem}_n.dds", f"{stem}_n.dds"),
                    (f"textures/{stem}_m.dds", f"{stem}_m.dds"),
                    (f"textures/{stem}_reg_mask.dds", f"{stem}_reg_mask.dds"),
                ]

            # Store both paths and filenames
            item["tex_source"] = "binary" if targeted else "default"
            item["texture_data"] = dds_data  # [(full_path, filename), ...]
            dds_names = [fname for _, fname in dds_data]
            item["textures"] = dds_names  # Keep for backward compatibility
            results = find_textures_in_folder(res, dds_names) if res and os.path.isdir(res) and dds_names else {}
            self.after(0, self._on_texture_search_done, item, results)
        threading.Thread(target=worker, daemon=True).start()

    def _on_texture_search_done(self, item, results):
        if self._sel_res is not item:
            return
        self._texture_results = results
        self._res_card.show(item, texture_results=results)
        found = sum(1 for v in results.values() if v)
        total = len(results)
        self._set_status(
            f"Resource: {item['filename']}  [{item['slot']}]  -- {found}/{total} textures found",
            color=SUCCESS if found == total else (WARN if found else ERROR))
        # Now that textures are populated, pre-fill the name and build the checkbox rows
        new_stem = item["path"].stem
        self._new_mg_var.set(new_stem)
        # Initialize undo state for this new selection
        self._undo_stack.clear()
        self._redo_stack.clear()
        self._last_value = new_stem
        self._tex_unlinked.clear()
        self._on_mg_name_change()

    def _on_mod_select(self, item):
        self._sel_mod = item
        self._set_status(f"Mod: {item['filename']}  [{item['slot']}]")

    # ── Copy & rename ──────────────────────────────────────────────────────────

    def _copy_to_mod(self):
        item = self._sel_res
        if not item:
            messagebox.showwarning("Nothing selected",
                                "Select a file in the Resource Folder panel first.")
            return
        mod = self._mod_var.get().strip()
        if not mod:
            messagebox.showerror("No mod folder", "Set a Mod Output Folder first.")
            return

        new_mg_stem = self._new_mg_var.get().strip()
        if not new_mg_stem:
            messagebox.showerror("No name", "Enter a new graph file name.")
            return

        # Strip extension if the user typed it in (e.g. "foo.mgraphobject" -> "foo")
        if new_mg_stem.lower().endswith(".mgraphobject"):
            new_mg_stem = new_mg_stem[: -len(".mgraphobject")]

        src         = item["path"]
        old_mg_stem = src.stem
        gear_swap   = self._gear_swap_only.get()
        mod_folder  = Path(mod)

        # Build a map of old_filename -> (original_full_path, new_full_path) for patching
        texture_path_map = {}  # old_filename -> (old_full_path, new_full_path)
        
        if not gear_swap:
            # ── Derive texture rename map - handles both auto and manual naming
            tex_pairs = self._derive_texture_names(new_mg_stem)  # [(old, new), ...] for auto mode
            length_errors = []
            tex_rename_map = {}  # old_name -> new_name
            
            for o, n, _linked in tex_pairs:
                # Check if manual naming is enabled for this texture
                is_manual = self._tex_manual_vars.get(o, tk.BooleanVar(value=False)).get()
                is_auto = self._tex_check_vars.get(o, tk.BooleanVar(value=True)).get()
                
                if is_manual:
                    # Use manual name from Entry widget
                    entry = self._tex_manual_entries.get(o)
                    if not entry:
                        messagebox.showerror("Error", f"Manual entry widget not found for '{o}'.")
                        return
                    manual_stem = entry.get().strip()
                    if not manual_stem:
                        messagebox.showerror("Empty manual name", 
                            f"Manual name for '{o}' cannot be empty.")
                        return
                    suffix = get_texture_suffix(o)
                    new_name = manual_stem + suffix
                    tex_rename_map[o] = new_name
                    
                    # Check length
                    old_base, old_suffix = get_texture_base_and_suffix(o)
                    if len(manual_stem) != len(old_base):
                        length_errors.append(
                            f"'{old_base}' ({len(old_base)})  ->  '{manual_stem}' ({len(manual_stem)})"
                        )
                elif is_auto:
                    # Use auto-derived name
                    if o != n:  # Only add if there's an actual change
                        tex_rename_map[o] = n
                        # Check length
                        old_base, old_suffix = get_texture_base_and_suffix(o)
                        new_base, new_suffix = get_texture_base_and_suffix(n)
                        if len(old_base) != len(new_base):
                            length_errors.append(
                                f"'{old_base}' ({len(old_base)})  ->  '{new_base}' ({len(new_base)})"
                            )
            
            if length_errors:
                messagebox.showerror(
                    "Length mismatch",
                    "Derived texture names must be exactly the same length as originals.\n\n"
                    + "\n".join(length_errors))
                return
            
            # Build texture path map from the stored texture_data
            if "texture_data" in item:
                for old_full_path, old_filename in item["texture_data"]:
                    if old_filename in tex_rename_map:
                        new_filename = tex_rename_map[old_filename]
                        # Replace the old filename in the path with the new one
                        new_full_path = old_full_path.replace(old_filename, new_filename)
                        texture_path_map[old_filename] = (old_full_path, new_full_path)
        else:
            tex_rename_map = {}

        # ── Graph file length warning (skipped in gear swap mode — any length is fine)
        new_mg_name = new_mg_stem + src.suffix
        if not gear_swap and len(new_mg_stem) != len(old_mg_stem):
            diff = len(new_mg_stem) - len(old_mg_stem)
            sign = "+" if diff > 0 else ""
            themed_error(self,
                "Graph File Name Length Mismatch",
                f"The new graph filename must be exactly the same length as the original.\n\n"
                f"  Old:  {old_mg_stem}  ({len(old_mg_stem)} chars)\n"
                f"  New:  {new_mg_stem}  ({len(new_mg_stem)} chars)  [{sign}{diff}]\n\n"
                f"Adjust the name so both are the same length.")
            return

        # ── Determine output paths — all files go to MOD FOLDER ROOT (not source folder)
        dst_mgraph = mod_folder / new_mg_name

        # Texture copies only relevant when not in gear swap mode
        tex_copies = []  # (src_path, dst_path, old_name, new_name, folder_path)
        if not gear_swap:
            for old_name, new_name in tex_rename_map.items():
                tex_src = self._texture_results.get(old_name)
                if tex_src is None:
                    continue  # not found on disk, skip
                
                # Get the folder structure from the mgraph file
                if old_name in texture_path_map:
                    _, new_full_path = texture_path_map[old_name]
                    # Extract folder path from the full path
                    folder_path = "/".join(new_full_path.split("/")[:-1])
                    # Create full destination path preserving folder structure
                    dst_tex = mod_folder / folder_path.replace("/", os.sep) / new_name
                else:
                    # Fallback: if no path info, just put in mod folder root
                    dst_tex = mod_folder / new_name
                    folder_path = ""
                
                tex_copies.append((tex_src, dst_tex, old_name, new_name, folder_path))

        # ── Overwrite check
        all_dsts = [dst_mgraph] + [d for _, d, _, _, _ in tex_copies]
        existing = [d for d in all_dsts if d.exists()]
        if existing:
            names = "\n".join(f"  {p.name}" for p in existing)
            if not messagebox.askyesno(
                "Overwrite?",
                f"These files already exist in the mod folder:\n\n{names}\n\nOverwrite?"):
                return

        # ── Read the .mgraphobject binary
        try:
            mg_data = src.read_bytes()
        except Exception as e:
            messagebox.showerror("Read error", f"Could not read {src.name}:\n{e}")
            return

        # ── Patch internal DDS refs only when not in gear swap mode
        # We need to patch FULL PATHS in the binary, not just filenames
        if not gear_swap:
            try:
                for old_name in tex_rename_map.keys():
                    if old_name in texture_path_map:
                        old_full_path, new_full_path = texture_path_map[old_name]
                        mg_data = patch_binary_string(mg_data, old_full_path, new_full_path)
            except ValueError as e:
                messagebox.showerror("Patch error", str(e))
                return

        # ── Execute all writes
        ok, failed = [], []

        # Write (patched) + renamed .mgraphobject to MOD FOLDER
        try:
            dst_mgraph.parent.mkdir(parents=True, exist_ok=True)
            dst_mgraph.write_bytes(mg_data)
            ok.append(dst_mgraph.name)
        except Exception as e:
            failed.append(f"{dst_mgraph.name}: {e}")

        # Copy textures (renamed) to MOD FOLDER with folder structure — skipped in gear swap mode
        for tex_src, tex_dst, old_name, new_name, folder_path in tex_copies:
            try:
                tex_dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(tex_src, tex_dst)
                if folder_path:
                    ok.append(f"{old_name} -> {folder_path}/{new_name}")
                else:
                    ok.append(f"{old_name} -> {new_name}")
            except Exception as e:
                failed.append(f"{old_name}: {e}")

        if ok and not failed:
            self._set_status(
                f"Done -- {len(ok)} file(s) written to mod folder"
                + (" (gear swap only)." if gear_swap else " with renamed textures."),
                color=SUCCESS)
        elif ok:
            self._set_status(f"Done with errors -- {len(failed)} failed.", color=WARN)
            messagebox.showwarning("Partial success", "Failed:\n" + "\n".join(failed))
        else:
            self._set_status("Copy failed.", color=ERROR)
            messagebox.showerror("Copy failed", "\n".join(failed))

        self._scan_mod(mod)

    # ── Undo/Redo ──────────────────────────────────────────────────────────────────
    
    def _undo(self, event=None):
        """Undo the last change to the graph name entry."""
        if not self._undo_stack:
            return "break"  # Prevent default behavior
        
        # Push current value to redo stack
        current = self._new_mg_var.get()
        self._redo_stack.append(current)
        
        # Pop from undo stack and set
        previous = self._undo_stack.pop()
        self._undo_in_progress = True
        self._new_mg_var.set(previous)
        self._last_value = previous
        self._undo_in_progress = False
        
        return "break"  # Prevent default Tkinter undo
    
    def _redo(self, event=None):
        """Redo the last undone change to the graph name entry."""
        if not self._redo_stack:
            return "break"  # Prevent default behavior
        
        # Push current value to undo stack
        current = self._new_mg_var.get()
        self._undo_stack.append(current)
        
        # Pop from redo stack and set
        next_value = self._redo_stack.pop()
        self._undo_in_progress = True
        self._new_mg_var.set(next_value)
        self._last_value = next_value
        self._undo_in_progress = False
        
        return "break"  # Prevent default Tkinter redo

    # ── Status ─────────────────────────────────────────────────────────────────

    def _set_status(self, msg, color=MUTED):
        self._status_var.set(msg)
        self._status_lbl.config(fg=color)


# ── Entry point ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    App().mainloop()